version: '3.7'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: convercoin_app
    container_name: convercoin_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - convercoin_network
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=convercoin
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    ports:
      - "8000:8000"

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: convercoin_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: convercoin
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - convercoin_network

volumes:
  dbdata:

networks:
  convercoin_network:
    driver: bridge
